//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_attempts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question_attempts()
        {
            this.question_attempt_steps = new HashSet<question_attempt_steps>();
        }
    
        public int question_attemptsId { get; set; }
        public int questionId { get; set; }
        public Nullable<decimal> maxmark { get; set; }
        public Nullable<decimal> minfraction { get; set; }
        public Nullable<decimal> maxfraction { get; set; }
        public string questionssummary { get; set; }
        public string rightanswer { get; set; }
    
        public virtual question question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_attempt_steps> question_attempt_steps { get; set; }
    }
}
