//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.question_answers = new HashSet<question_answers>();
            this.question_attempts = new HashSet<question_attempts>();
            this.quiz_slots = new HashSet<quiz_slots>();
        }
    
        public int questionId { get; set; }
        public int categoryId { get; set; }
        public string name { get; set; }
        public string questiontext { get; set; }
        public Nullable<decimal> defaultmark { get; set; }
        public Nullable<System.DateTime> timecreated { get; set; }
    
        public virtual course_categories course_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_answers> question_answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_attempts> question_attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_slots> quiz_slots { get; set; }
    }
}
