//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quiz()
        {
            this.quiz_attempts = new HashSet<quiz_attempts>();
            this.quiz_grades = new HashSet<quiz_grades>();
            this.quiz_slots = new HashSet<quiz_slots>();
        }
    
        public int quizId { get; set; }
        public int courseId { get; set; }
        public string name { get; set; }
        public Nullable<int> attempts { get; set; }
        public Nullable<decimal> sumgrades { get; set; }
        public Nullable<decimal> grade { get; set; }
        public Nullable<System.DateTime> timecreated { get; set; }
    
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_attempts> quiz_attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_grades> quiz_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_slots> quiz_slots { get; set; }
    }
}
