//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_enrolments
    {
        public int user_enrolmentsId { get; set; }
        public int userId { get; set; }
        public Nullable<System.DateTime> timestart { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
        public Nullable<System.DateTime> timecreated { get; set; }
        public Nullable<System.DateTime> timemodified { get; set; }
    
        public virtual user user { get; set; }
    }
}
