//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_info_field()
        {
            this.user_info_data = new HashSet<user_info_data>();
        }
    
        public int user_info_fieldId { get; set; }
        public string shortname { get; set; }
        public string name { get; set; }
        public string datatype { get; set; }
        public string description { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<bool> visible { get; set; }
        public string defaultdata { get; set; }
        public string param1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_info_data> user_info_data { get; set; }
    }
}
