//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_completions
    {
        public int course_completionsId { get; set; }
        public int userId { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<System.DateTime> timeenrolled { get; set; }
        public Nullable<System.DateTime> timestarted { get; set; }
        public System.DateTime timecompleted { get; set; }
    
        public virtual course course { get; set; }
        public virtual user user { get; set; }
    }
}
