//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_attempt_steps
    {
        public int question_attempt_stepsId { get; set; }
        public int question_attemptsId { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> timecreated { get; set; }
        public int userId { get; set; }
        public Nullable<int> fraction { get; set; }
    }
}
