//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_attempts
    {
        public int question_attemptsId { get; set; }
        public int questionId { get; set; }
        public Nullable<decimal> maxmark { get; set; }
        public Nullable<decimal> minfraction { get; set; }
        public Nullable<decimal> maxfraction { get; set; }
        public string questionssummary { get; set; }
        public string rightanswer { get; set; }
    
        public virtual question question { get; set; }
    }
}
