//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz_attempts
    {
        public int quiz_attempts1 { get; set; }
        public int quizId { get; set; }
        public int userId { get; set; }
        public Nullable<int> attempt { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> timestart { get; set; }
        public Nullable<System.DateTime> timefinish { get; set; }
        public Nullable<int> sumgrades { get; set; }
    
        public virtual quiz quiz { get; set; }
        public virtual user user { get; set; }
    }
}
