//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_assignments
    {
        public int role_assignmentsId { get; set; }
        public int roleId { get; set; }
        public string shortname { get; set; }
    
        public virtual role role { get; set; }
    }
}
