//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class templateColumn
    {
        public int templateColumnId { get; set; }
        public Nullable<int> columnTranslationId { get; set; }
        public Nullable<int> templateId { get; set; }
    
        public virtual columnTranslation columnTranslation { get; set; }
        public virtual template template { get; set; }
    }
}
