//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSalePerson
    {
        public int TestSalePersonId { get; set; }
        public string branch { get; set; }
        public string region { get; set; }
        public int TestPersonId { get; set; }
    
        public virtual TestPerson TestPerson { get; set; }
    }
}
