//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportDeport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info_data
    {
        public int user_info_dataId { get; set; }
        public int userId { get; set; }
        public int user_info_fieldId { get; set; }
        public string data { get; set; }
    
        public virtual user user { get; set; }
        public virtual user_info_field user_info_field { get; set; }
    }
}
